version: '3.8'

services:
  nestjs_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
      PORT: 3000
    volumes:
      - ./src:/app/src
  nestjs_mysql_db:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nestjs_mysql_db
      MYSQL_USER: nestjs_user
      MYSQL_PASSWORD: nestjs_password
      MYSQL_TCP_PORT: 3306
