version: '3.8'

services:
  nestjs_api_prod:
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - 3001:3001
    environment:
      NODE_ENV: production
      PORT: 3001
    volumes:
      - ./src:/app/src
